services:
  # A Docker web service
  - type: web
    name: tgdrive
    repo: https://github.com/TechShreyash/TGDrive
    runtime: python
    branch: main
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKENS
        sync: false
      - key: STORAGE_CHANNEL
        sync: false
      - key: DATABASE_BACKUP_MSG_ID
        sync: false
